dist: trusty
language: node_js
cache:
  directories:
  - node_modules
node_js:
- stable
before_script:
- npm install -g httpserver
- cd dist && httpserver -p 8084 &
script:
- npx cypress run
branches:
only: master
